# @package _group_
_target_: mbrl.models.PlaNetModel
obs_shape: [1, 64, 64]
obs_encoding_size: 256
encoder_config:
  - [1, 32, 4, 2]
  - [32, 64, 4, 2]
  - [64, 64, 4, 2]
  - [64, 64, 4, 2]
decoder_config:
  - [256, 1, 1]
  - - [256, 128, 5, 2]
    - [128, 64, 5, 2]
    - [64, 32, 6, 2]
    - [32, 1, 6, 2]
action_size: ???
hidden_size_fcs: 128
belief_size: 128
latent_state_size: 30
device: ${device}
min_std: 0.1
free_nats: 3.0
kl_scale: 1.0
grad_clip_norm: 1000.0
